name: cqtdeployerexample # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: simple example for packing with cqtdeployer # 79 char long summary
description: |
  simple example for packing with cqtdeployer

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


apps:
  cqtdeployerexample:
    command: desktop-launch $SNAP/TestQMLWidgets.sh

    plugs: [desktop, unity7, home, opengl, x11, wayland]


parts:
  cqtdeployerexample:
    # See 'snapcraft plugins'
    plugin: dump
    source: distro
    after: [wrapper, libsgl]
    
  wrapper:
    plugin: dump
    source: wrapper
    
  libsgl:
    plugin: nil
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libx11-xcb1
      - libglu1-mesa
      - libxrender1
      - libxi6
      - libegl1-mesa
      - fontconfig
      - libgl1-mesa-dri
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - libgtk2.0-0
      - xdg-user-dirs
      - libxrandr2
      - libwayland-cursor0
      - libwayland-egl1
      - libpq5
